### PR TITLE
Update and overhaul text.

### PR DESCRIPTION
**Pull request by ianmacd**
* Improve clarity.

* Remove some duplicated information (some duplication is necessary, because readers are not required to read all sections).

* Greatly expand Step 1, 'Obtaining a server', to promote better network decentralisation at all levels.

* Include usage of oxend-download-lmdb for rapid blockchain syncing.

* Increase minimum storage requirement to 40 Gb.

* Remove bandwidth column from popular provider table. Figures given were inaccurate and did not meet minimum requirement (100Mbit) listed elsewhere.

* Add Linode to popular provider table.

* Fix inconsistent use of capitalisation.

* Fix inconsistent use of units.

* Place hotkeys between backticks.

### CODE REVIEW

**Comment by ianmacd** [comment]
I would ideally like to remove the table of popular VPS providers altogether.

Although the text explains that none of the providers in the table is officially endorsed, the table's very inclusion undoubtedly steers users towards these providers, which is bad for diversity.

On the other hand, removing the table may constitute an unacceptable raising of the threshold to entry. In other words, the presence of such a table may make the difference between staking and not staking for some people.

**Comment by KeeJef** [comment]
I'd prefer to leave the table gives new users a good idea of some of the providers if they have no clue where to start

**Comment by ianmacd** [comment]
> I'd prefer to leave the table gives new users a good idea of some of the providers if they have no clue where to start, otherwise LGTM

No worries. That concern is exactly why I didn't remove the table without soliciting your input,

I have one or two more changes coming, as I realised this morning that I forgot to include a couple of points I wanted to make.

I'll add those here and rebase, unless you'd rather merge straight away, in which case I'll add the rest separately. Nothing crucial, so not worth delaying if you're keen to get these changes live.

**Review by ianmacd — COMMENTED** [review]
Sweet.

I wasn't sure the Discord bot was still actively developed.

**Comment by ianmacd** [comment]
I've made one further small change to the text, @KeeJef .

You gave your LGTM approval earlier today, but the PR remains open. I assume it will be merged in due course.

Thanks for opening up the docs. It's another good way for the community to contribute to the project.

**Pull request merged**
